# Generated by Django 5.1.5 on 2025-02-07 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcareprofile',
            name='h_email',
        ),
        migrations.RemoveField(
            model_name='healthcareprofile',
            name='h_name',
        ),
    ]
