# Generated by Django 5.1.6 on 2025-03-06 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0008_familymember_chronicillness_followuppatient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fever_7_days_or_more_male_5_or_less', models.IntegerField(default=0)),
                ('fever_7_days_or_more_male_above_5', models.IntegerField(default=0)),
                ('fever_7_days_or_more_female_5_or_less', models.IntegerField(default=0)),
                ('fever_7_days_or_more_female_above_5', models.IntegerField(default=0)),
                ('fever_less_than_7_days_male_5_or_less', models.IntegerField(default=0)),
                ('fever_less_than_7_days_male_above_5', models.IntegerField(default=0)),
                ('fever_less_than_7_days_female_5_or_less', models.IntegerField(default=0)),
                ('fever_less_than_7_days_female_above_5', models.IntegerField(default=0)),
                ('fever_with_rash', models.IntegerField(default=0)),
                ('fever_with_bleeding', models.IntegerField(default=0)),
                ('fever_with_altered_sensorium', models.IntegerField(default=0)),
                ('cough_2_weeks_or_less_with_fever', models.IntegerField(default=0)),
                ('cough_2_weeks_or_less_without_fever', models.IntegerField(default=0)),
                ('cough_more_than_2_weeks_with_fever', models.IntegerField(default=0)),
                ('cough_more_than_2_weeks_without_fever', models.IntegerField(default=0)),
                ('loose_watery_stools_with_blood_less_than_2_weeks', models.IntegerField(default=0)),
                ('loose_watery_stools_without_blood_less_than_2_weeks', models.IntegerField(default=0)),
                ('jaundice_less_than_4_weeks', models.IntegerField(default=0)),
                ('acute_flaccid_paralysis', models.IntegerField(default=0)),
                ('malaria_vivax_rdt', models.IntegerField(default=0)),
                ('malaria_falciparum_rdt', models.IntegerField(default=0)),
                ('malaria_mixed_rdt', models.IntegerField(default=0)),
                ('animal_bite_snake', models.IntegerField(default=0)),
                ('animal_bite_dog', models.IntegerField(default=0)),
                ('animal_bite_other', models.IntegerField(default=0)),
                ('leptospirosis_rdt', models.IntegerField(default=0)),
                ('total_cases', models.IntegerField(default=0)),
                ('total_deaths', models.IntegerField(default=0)),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_surveys', to='health_app.household')),
            ],
        ),
    ]
