# Generated by Django 5.1.6 on 2025-03-07 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0011_maternalvisitschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildGrowthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('guardian_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('head_circumference', models.FloatField()),
                ('mid_upper_arm_circumference', models.FloatField()),
                ('exclusive_breastfeeding_till_6_months', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('complementary_feeding_started', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('vitamin_a_supplementation', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('immunization_status', models.CharField(choices=[('Up to Date', 'Up to Date'), ('Delayed', 'Delayed'), ('Missed', 'Missed')], max_length=20)),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
