# Generated by Django 5.1.6 on 2025-03-07 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0012_childgrowthrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('contact_number', models.CharField(max_length=15)),
                ('location', models.TextField()),
                ('address', models.TextField()),
                ('vaccine_name', models.CharField(choices=[('BCG', 'BCG'), ('OPV', 'OPV'), ('DTP', 'DTP'), ('Measles', 'Measles'), ('COVID-19', 'COVID-19')], max_length=50)),
                ('vaccination_date', models.DateField()),
                ('route_of_administration', models.CharField(choices=[('Oral', 'Oral'), ('Intramuscular', 'Intramuscular'), ('Subcutaneous', 'Subcutaneous')], max_length=50)),
                ('vaccinator_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
