# Generated by Django 5.1.6 on 2025-03-07 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0013_vaccinationrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('age_group', models.CharField(choices=[('0-1', '0-1 month'), ('1.5', '1.5 months'), ('2.5', '2.5 months'), ('3.5', '3.5 months'), ('9', '9 months'), ('16-24', '16-24 months'), ('5-6', '5-6 years'), ('10', '10 years'), ('16', '16 years')], max_length=10)),
                ('vaccines', models.TextField()),
                ('vaccination_date', models.DateField(blank=True, null=True)),
                ('vaccinator_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
