# Generated by Django 5.1.6 on 2025-03-10 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0016_bedridden'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedriddenVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('visit_time', models.TimeField()),
                ('assigned_health_worker', models.CharField(choices=[('PHN', 'Public Health Nurse'), ('JHI', 'Junior Health Inspector')], max_length=3)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('assigned_asha_worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='health_app.ashaworkerprofile')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_app.bedridden')),
            ],
        ),
    ]
