# Generated by Django 5.1.6 on 2025-03-12 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0017_bedriddenvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255)),
                ('brand_name', models.CharField(max_length=255)),
                ('medicine_code', models.CharField(max_length=100)),
                ('drug_code', models.CharField(max_length=100)),
                ('batch_lot_number', models.CharField(max_length=100)),
                ('strength_concentration', models.CharField(max_length=50)),
                ('inactive_ingredients', models.TextField()),
                ('dosage_form', models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Syrup', 'Syrup'), ('Injection', 'Injection'), ('Cream', 'Cream')], max_length=50)),
                ('route_of_administration', models.CharField(choices=[('Oral', 'Oral'), ('IV', 'Intravenous'), ('IM', 'Intramuscular'), ('Topical', 'Topical')], max_length=50)),
                ('recommended_dosage', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('manufacturing_date', models.DateField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.IntegerField()),
                ('stock_status', models.BooleanField(default=True)),
                ('fk_pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_app.pharmacistprofile')),
            ],
        ),
    ]
