# Generated by Django 5.1.6 on 2025-03-14 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0018_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_to_take', models.IntegerField(choices=[(1, '1 Day'), (2, '2 Days'), (3, '3 Days'), (4, '4 Days'), (5, '5 Days'), (6, '6 Days'), (7, '1 Week')])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('fk_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_given', to='health_app.doctorprofile')),
                ('fk_medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_app.medicine')),
                ('fk_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_received', to='health_app.patientprofile')),
            ],
        ),
    ]
