# Generated by Django 5.1.6 on 2025-03-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0019_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='disease_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
