# Generated by Django 5.1.6 on 2025-03-15 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0020_prescription_disease_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token_No',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_number', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('fk_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_doct', to='health_app.doctorprofile')),
                ('fk_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_pat', to='health_app.patientprofile')),
            ],
        ),
    ]
